---
- name: Install required dependencies
  apt:
    name:
      - wget
      - apt-transport-https
      - software-properties-common
    state: present
    update_cache: yes


- name: Add Microsoft GPG key for Ubuntu
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present


- name: Add Microsoft repository for Ubuntu
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-focal-prod focal main"
    state: present


- name: Update apt cache
  apt:
    update_cache: yes


- name: Install PowerShell
  apt:
    name: powershell
    state: present

