# roles/apache/tasks/main.yml

- name: Install Apache on Ubuntu/Debian
  apt:
    name: apache2
    state: present
  when: ansible_os_family == 'Debian'

- name: Install Apache on RHEL/CentOS
  yum:
    name: httpd
    state: present
  when: ansible_os_family == 'RedHat'

- name: Ensure Apache is running and enabled
  service:
    name: "{{ apache_service_name }}"
    state: started
    enabled: yes

- name: Deploy custom index.html using template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Apache Restart
