print("My Name is Sumit")
print("My Friend is Shyam")
print("Ka karoge Shyam, itne paise ka 50% muze donate kar do")
print("Scan and pay")
print("Jaldi paise bhejo")
print("My PhonePay ID 7558614009")