- name: Install Apache on linux VM
  hosts: managed_nodes
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:
    - name: Install Apache on Ubuntu (os_family == 'debian')
      apt:
        name: apache2
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Apache on RHEL/Centos
      yum:
        name: httpd
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Create changes in index.html file
      copy:
        content: "Hello, Install and changes made in managed_nodes and working fine"
        dest: /var/www/html/index.html
      notify: Apache Restart

  handlers:
    - name: Apache Restart
      service:
        name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
        state: restarted

