# create_user_playbook.yml
---
- name: Create user on managed VMs
  hosts: managed_nodes
  become: yes
  become_method: sudo
  vars:
    ansible_user: thelkar_sumit
  vars_files:
    - ../vaults/01_create_user_vault.yml
  roles:
    - ../roles/02_create_user
