---
- name: Update the system based on OS
  hosts: managed_nodes
  become: yes
  become_method: sudo  # Use 'sudo' for privilege escalation
  gather_facts: yes  # Ensure facts are gathered, if necessary

  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Update packages on Ubuntu
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"
      tags: 
        - debian
      register: debian_update_result

    - name: Update packages on RHEL
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"
      tags:
        - redhat
      register: redhat_update_result

    - name: Notify if no packages were updated on Debian
      debug:
        msg: "No packages were updated on Debian."
      when: ansible_os_family == "Debian" and debian_update_result.changed == false
      tags:
        - debian

    - name: Notify if no packages were updated on RHEL
      debug:
        msg: "No packages were updated on RHEL."
      when: ansible_os_family == "RedHat" and redhat_update_result.changed == false
      tags:
        - redhat
