---
- name: Update the system based on OS
  hosts: all
  become: yes
  tasks:
    - name: Update packages on Ubuntu
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Update packages on RHEL
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"
