# roles/create_user/tasks/main.yml
---
- name: Create a new user
  user:
    name: "{{ username }}"
    password: "{{ user_password | password_hash('sha512') }}"
    state: present
    shell: /bin/bash

- name: Ensure the user is in the sudoers group (if necessary)
  user:
    name: "{{ username }}"
    groups: sudo
    append: yes
