vm_name = "jenkin-cicd-demo1"
zone = "northamerica-northeast1-a"
image = "debian-cloud"
machine_type = "e2-medium"
network = "jenkins-test-vpc"
subnetwork = "jenkins-test-subnetwork"
project_id = "shyamkprj"
subnetwork_project = "shyamkprj"
