pipeline {
    agent any
    
    environment {
        SCANNER_HOME=tool 'SonarQube-Scanner'
        PROJECT_ID='shyamkprj'
        CLIENT_EMAIL='sumit-jenkins-learning@shyamkprj.iam.gserviceaccount.com'
        GCLOUD_CREDS=credentials('gcp-id')
        IMAGE_NAME = 'hello-world'
        DOCKER_IMAGE = ''
      }
    
  tools {
        maven 'Maven'
    }
    
 stages {
/*         stage('sonarqube-analysis') {
            steps {
                withSonarQubeEnv('SonarQube-server') {
                 sh 'mvn clean verify sonar:sonar \
                      -Dsonar.projectKey=06-HelloWorld-DockerImage-Push-GCP \
                      -Dsonar.host.url=http://34.88.208.170:9000 \
                      -Dsonar.login=sqp_c13007b8bae2a0c234171e2b18175f794e35d2be'
                }
            }
        } */
        
/*      stage('Test') {
            steps {
                // Define steps for the Test stage
                echo 'Running tests...'
                sh  'mvn test'
            }
        }
      */
    stage('Build') {
            steps {
                // Define steps for the Build stage
                echo 'Building the project...'
                sh 'mvn clean package'
            }
        }
     
    stage('Docker Build') {
            steps {
                script {
                    // Build the Docker image
                    withCredentials([file(credentialsId: 'gcp-id', variable: 'KEY_FILE')]) {
                            sh '''
                            gcloud auth activate-service-account --key-file="$KEY_FILE"
                            '''
                            sh 'docker build -t us-central1-docker.pkg.dev/peak-axiom-426310-b1/docker-image-push-01/helloworld .'
                            }
                }
            }
        }
     
    stage('Docker Push') {
            steps {
                script {
                        sh 'gcloud auth configure-docker \
                            us-central1-docker.pkg.dev'
                        sh 'docker push us-central1-docker.pkg.dev/peak-axiom-426310-b1/docker-image-push-01/helloworld'
                }
            }
        }
    }
    post {
        success {
            // Actions to take if the pipeline succeeds
            echo 'Pipeline succeeded!'
            // You can also send an email notification on success
            mail to: 'thelkarsc@gmail.com',
                 subject: "Pipeline Succeeded: ${currentBuild.fullDisplayName}",
                 body: "The pipeline ${env.BUILD_URL} has successfully completed."
        }
        failure {
            // Actions to take if the pipeline fails
            echo 'Pipeline failed!'
            // You can also send an email notification on failure
            mail to: 'thelkarsc@gmail.com',
                 subject: "Pipeline Failed: ${currentBuild.fullDisplayName}",
                 body: "The pipeline ${env.BUILD_URL} has failed. Check the logs for details."
        }
    }
}
