# tasks/main.yml
---

- name: Install PowerShell on Debian
  ansible.builtin.apt:
    name: "powershell"
    state: present
    update_cache: yes
    when: ansible_os_family == 'Debian'
    
- name: Install PowerShell on RHEL
  when: os_facts.ansible_distribution == "RedHat"
  ansible.builtin.yum:
    name: "powershell"
    state: present
    when: ansible_os_family == 'RedHat'



