---
- name: Install Apache on Ubuntu/Debian
  apt:
    name: powershell
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install Apache on RHEL/CentOS
  yum:
    name: powershell
    state: present
  when: ansible_os_family == 'RedHat'
