---
- name: Install PowerShell on Ubuntu/Debian
  apt:
    name: powershell
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'
  # Ensure that the Microsoft repository is added for PowerShell
  become: yes
  become_method: sudo
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -rs)-prod $(lsb_release -cs) main"
    state: present

- name: Install PowerShell on CentOS/RHEL
  yum:
    name: powershell
    state: present
  when: ansible_os_family == 'RedHat'
  # Ensure that the Microsoft repository is added for PowerShell
  become: yes
  become_method: sudo
  yum_repository:
    name: microsoft
    description: Microsoft PowerShell Repo
    baseurl: https://packages.microsoft.com/yumrepos/microsoft-centos7-prod
    enabled: 1
    gpgcheck: 1
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
