---
- name: Add Microsoft GPG key for Ubuntu/Debian
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Microsoft repository for Ubuntu/Debian
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -rs)-prod $(lsb_release -cs) main"
    state: present
  when: ansible_os_family == 'Debian'

- name: Install PowerShell on Ubuntu/Debian
  apt:
    name: powershell
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'